default_stages: [commit, push]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: ["--django"]
      - id: check-yaml

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 4.0.1
      hooks:
        - id: flake8
          language: system
          types: [python]
          args: ["--max-line-length=120"]
